# Podfile
# CocoaPods dependency manager for iOS project

platform :ios, '11.0'

# Flutter Pod
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'FLUTTER_ROOT=\$(SOURCE_ROOT)/Flutter',
        'FLUTTER_APPLICATION_PATH=\$(SOURCE_ROOT)/..',
        'FLUTTER_TARGET=\$(FLUTTER_APPLICATION_PATH)/lib/main.dart',
        'FLUTTER_BUILD_DIR=build',
        'SYMROOT=\${SOURCE_ROOT}/../build/ios',
        'FLUTTER_BUILD_NAME=1.0.0',
        'FLUTTER_BUILD_NUMBER=1',
      ]
    end
  end
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_root = File.expand_path(File.join(packages_dir, '.symlinks', 'flutter'))
  load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper')

  flutter_ios_podfile_setup

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
