// ignore_for_file: type=lint
//
// ============================================================================
//  PLACEHOLDER Firebase configuration.
//
//  Replace this file with the one generated by the FlutterFire CLI:
//
//     dart pub global activate flutterfire_cli
//     flutterfire configure
//
//  Until you do, the app detects the placeholder values and runs in a local
//  DEMO mode (mock auth + in-memory data) so you can preview every screen.
// ============================================================================

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  /// True when the file still contains placeholder credentials.
  static bool get isPlaceholder =>
      currentPlatform.apiKey.startsWith('REPLACE_');

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME_ANDROID_API_KEY',
    appId: 'REPLACE_ME_ANDROID_APP_ID',
    messagingSenderId: 'REPLACE_ME_SENDER_ID',
    projectId: 'aden-digital',
    storageBucket: 'aden-digital.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME_IOS_API_KEY',
    appId: 'REPLACE_ME_IOS_APP_ID',
    messagingSenderId: 'REPLACE_ME_SENDER_ID',
    projectId: 'aden-digital',
    storageBucket: 'aden-digital.appspot.com',
    iosBundleId: 'ye.gov.aden.adenDigital',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME_WEB_API_KEY',
    appId: 'REPLACE_ME_WEB_APP_ID',
    messagingSenderId: 'REPLACE_ME_SENDER_ID',
    projectId: 'aden-digital',
    storageBucket: 'aden-digital.appspot.com',
    authDomain: 'aden-digital.firebaseapp.com',
  );
}
